config:
  credentials: []
  project_repos:
    github.com/Deltares/Delft-FIAT:
      branch: master
      repo: https://github.com/Deltares/Delft-FIAT
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.0.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/Deltares/Delft-FIAT git:
        commands:
        - /usr/bin/env sh .sqa/script.sloppy-copper-chow.sh
        container: qc.acc_snazzy-champagne-newt
  QC.Doc:
    repos:
      github.com/Deltares/Delft-FIAT find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.scummy-razzmatazz-cuscus.sh
        container: qc.doc_beady-coral-goose
      github.com/Deltares/Delft-FIAT git:
        commands:
        - /usr/bin/env sh .sqa/script.chummy-persimmon-harrier.sh
        container: qc.doc_ugly-linen-tiger
  QC.Lic:
    repos:
      github.com/Deltares/Delft-FIAT licensee:
        commands:
        - /usr/bin/env sh .sqa/script.hazy-taupe-horse.sh
        container: qc.lic_ready-puce-chow
  QC.Ver:
    repos:
      github.com/Deltares/Delft-FIAT get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.nerdy-persimmon-hound.sh
        container: qc.ver_cranky-red-albatross
timeout: 5400
